name: Stryker
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  stryker:
    name: Stryker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Cache stryker incremental file
        uses: actions/cache@v3
        with:
          key: stryker-cache
          path: ./reports/stryker-incremental.json

      - name: Run stryker run
        run: npm run test:mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stryker-report
          path: reports/mutation
          retention-days: 30
